# Generated by Django 5.1.6 on 2025-02-26 04:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CapacityUtilization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("existing_capacity", models.PositiveIntegerField()),
                ("current_utilization", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("units_increase", models.PositiveIntegerField(default=0)),
                (
                    "supplier_chosen",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "order_cost",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PredictionsUtilization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("predicted_demand", models.PositiveIntegerField()),
                ("existing_capacity", models.PositiveIntegerField()),
                ("increase_capacity", models.CharField(max_length=255)),
                ("units_increase", models.PositiveIntegerField(default=0)),
                (
                    "supplier_chosen",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "order_cost",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("ordered", models.BooleanField(default=False)),
            ],
        ),
    ]
